- hosts: database
  gather_facts: true 
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: install centos 9 docker 
      import_role:
        name: "{{ roles_dir }}/postgres/centos"
      when: ansible_facts['distribution'] == "CentOS"           

    - name: install ubuntu docker 
      import_role:
        name: "{{ roles_dir }}/postgres/ubuntu"
      when: ansible_facts['distribution'] == "Ubuntu"           