- hosts: vbox 
  gather_facts: false 
  become: true
  become_user: root
  become_method: sudo
  vars_files:    
    - "{{container_dir}}/secrets.yml"
    - "{{container_dir}}/config.yml"      
  roles:
    - role: '{{ roles_dir }}/users'
    - role: '{{ roles_dir }}/php'
