root_dir: "/var/www/html"
http_port: "9000"
php_port: "9001"
pub_rsa_file: "/home/artur/.ssh/id_rsa.pub"  
http_service: |
  server {
        listen {{http_port}} default_server;
        listen [::]:{{http_port}} default_server;

        root  {{root_dir}};
        index index.html index.php;

        location ~ \.php$ {
            
            include /etc/nginx/fastcgi_params;
            fastcgi_pass    127.0.0.1:{{php_port}};
            fastcgi_index index.php;
            include fastcgi.conf;
        }
      } 
