---
# tasks file for roles/postgres/ubuntu
- name: apt install postgres
  ansible.builtin.apt:              
    name: postgresql
    state: present  
    fail_on_autoremove: yes


- name: start postgresql service
  ansible.builtin.service:
    name: postgresql              
    enabled: yes            
